// Shared data — productos, categorías, casos, testimonios, faqs

const CATEGORIAS = [
  { id: "all",         label: "Todo" },
  { id: "escritorio",  label: "Escritorio" },
  { id: "textil",      label: "Textil" },
  { id: "cocina",      label: "Cocina & viaje" },
  { id: "tech",        label: "Tech" },
  { id: "bolsas",      label: "Bolsas" },
  { id: "premium",     label: "Regalos premium" },
];

// Productos completos — cada uno con slug, descripción larga (SEO), materiales y técnicas
const PRODUCTOS = [
  {
    slug: "lapicero-metalico", name: "Lapicero metálico",
    fam: "escritorio", moq: 100, hot: false, tag: "Top ventas",
    lead: "El clásico que nunca falla. Cuerpo metálico, mecanismo retráctil, peso justo en la mano.",
    desc: "El lapicero metálico STAMP es nuestro best-seller corporativo. Cuerpo de metal con acabado mate, mecanismo retráctil silencioso y carga de tinta negra de larga duración. Pensado para regalo ejecutivo, kits de onboarding y giveaways donde la primera impresión cuenta.",
    materials: ["Cuerpo metálico (aluminio)", "Carga jumbo tinta negra", "Acabado mate o satinado"],
    colors: ["Blanco", "Negro", "Metal natural", "Azul navy"],
    tecnicas: ["Grabado láser (recomendado)", "Serigrafía a 1 color", "Impresión UV (logos full color)"],
    usos: ["Regalo ejecutivo", "Onboarding", "Eventos corporativos", "Premios de campaña"],
    imageLabel: "FOTO · Lapicero metálico negro con grabado",
    relacionados: ["libreta-a5", "llavero-pvc", "set-cuero-premium"],
  },
  {
    slug: "libreta-a5", name: "Libreta A5 personalizada",
    fam: "escritorio", moq: 50, hot: true,
    lead: "Tapa rígida, hojas bond crema, costura visible. La libreta que quieres en tu escritorio.",
    desc: "Libreta tamaño A5 con tapa rígida en folcote, encuadernación cosida y 100 hojas internas en papel bond crema de 80gr. Ideal para regalo corporativo, welcome packs y como herramienta diaria de tu equipo. Impresión exterior a todo color y cinta marcadora opcional.",
    materials: ["Tapa folcote rígida 350gr", "Hojas bond crema 80gr · 100 pp", "Encuadernación cosida", "Cinta marcadora"],
    colors: ["Negro", "Crema", "Rojo", "Verde bosque", "Azul navy"],
    tecnicas: ["Impresión CMYK exterior", "Hot stamping (dorado, plata, cobre)", "Grabado en relieve", "Estampado directo"],
    usos: ["Welcome kit", "Regalo ejecutivo", "Eventos y conferencias", "Material de trabajo"],
    imageLabel: "FOTO · Libreta A5 negra abierta + lapicero",
    relacionados: ["lapicero-metalico", "post-it-branded", "set-cuero-premium"],
  },
  {
    slug: "llavero-pvc", name: "Llavero PVC inyectado",
    fam: "escritorio", moq: 100,
    lead: "Forma a tu medida, relieve alto y bajo, color exacto. Lo más cercano a tener tu logo en miniatura.",
    desc: "Llavero en PVC micro inyectado, fabricado a partir del arte de tu marca. Permite formas irregulares, relieve alto y bajo, y mezcla de hasta 8 colores. Acabado de fábrica con anilla metálica de acero inoxidable.",
    materials: ["PVC micro inyectado", "Anilla metálica acero inox.", "Acabado relieve alto/bajo"],
    colors: ["Pantone a tu marca (hasta 8 colores)"],
    tecnicas: ["Inyección por molde (forma libre)", "Doble cara opcional", "Brillo en oscuridad disponible"],
    usos: ["Eventos masivos", "Giveaways", "Premios de campaña", "Merch retail"],
    imageLabel: "FOTO · Llavero PVC forma logo",
    relacionados: ["lanyard-sublimado", "lapicero-metalico", "tote-bag"],
  },
  {
    slug: "post-it-branded",
    name: "Post-it branded",
    fam: "escritorio", moq: 250,
    lead: "Las notas adhesivas que todo el mundo termina llevándose a casa.",
    desc: "Block de notas adhesivas con tapa branded. Hojas en colores pastel o blanco brillante. Pegamento de baja adherencia, removible y reposicionable.",
    materials: ["Hojas 75x75mm · 100 pp", "Tapa folcote", "Pegamento removible"],
    colors: ["Pastel rosa/amarillo/celeste", "Blanco brillante"],
    tecnicas: ["Impresión CMYK exterior", "Grabado bajo relieve en tapa"],
    usos: ["Onboarding", "Eventos", "Material de oficina"],
    imageLabel: "FOTO · Post-it branded apilados",
    relacionados: ["libreta-a5", "lapicero-metalico"],
  },
  {
    slug: "polo-pima",
    name: "Polo de algodón pima",
    fam: "textil", moq: 25, hot: true, tag: "Estrella",
    lead: "Pima peruano 100%. El que pides una vez y nunca quieres dejar de usar.",
    desc: "Polo manga corta en algodón pima peruano 100%, gramaje 180gr/m². Tejido suave, transpirable y de larga vida. Tallas de XS a 3XL. La elección obvia para uniformes corporativos, eventos y regalos premium para tu equipo.",
    materials: ["Algodón pima peruano 100%", "Tejido jersey 180 gr/m²", "Costura reforzada"],
    colors: ["Blanco", "Negro", "Gris jaspe", "Navy", "Verde bosque", "Pantone a medida (+MOQ)"],
    tecnicas: ["Bordado (recomendado)", "Estampado serigrafía", "Sublimación", "DTF para diseños full color"],
    usos: ["Uniformes corporativos", "Eventos y activaciones", "Regalos premium", "Merch retail"],
    imageLabel: "FOTO · Polo pima negro con bordado",
    relacionados: ["polo-dry-fit", "casaca-softshell", "gorra-plana"],
  },
  {
    slug: "casaca-softshell",
    name: "Casaca técnica softshell",
    fam: "textil", moq: 25,
    lead: "Capa exterior que aguanta lluvia ligera y viento. Sin sacrificar el corte.",
    desc: "Casaca técnica con tela softshell 3 capas, repelente al agua DWR y barrera cortavientos. Costuras selladas, cierre frontal YKK y bolsillos laterales con cierre. Personalización por bordado o transfer térmico.",
    materials: ["Softshell 3 capas DWR", "Cierre YKK", "Costuras selladas", "Forro micro polar"],
    colors: ["Negro", "Gris carbón", "Navy", "Verde militar"],
    tecnicas: ["Bordado pecho/espalda", "Transfer térmico", "Etiqueta tejida custom"],
    usos: ["Operaciones campo", "Eventos exteriores", "Regalo corporativo invierno", "Uniforme ejecutivo"],
    imageLabel: "FOTO · Casaca softshell negra · plano lay-flat",
    relacionados: ["polo-pima", "gorra-plana", "mochila-ejecutiva"],
  },
  {
    slug: "gorra-plana",
    name: "Gorra plana",
    fam: "textil", moq: 25,
    lead: "Visera plana, ajuste snapback, estructura firme. La que sí se la van a poner.",
    desc: "Gorra de 6 paneles con visera plana, snapback ajustable y estructura firme. Personalización principal por bordado 3D frontal. Forro interior con etiqueta branded opcional.",
    materials: ["Algodón 100%", "Visera plana rígida", "Ajuste snapback"],
    colors: ["Negro", "Blanco", "Navy", "Beige", "Bicolor a medida"],
    tecnicas: ["Bordado 3D frontal", "Bordado plano lateral/trasero", "Parche branded"],
    usos: ["Eventos y activaciones", "Merch retail", "Uniforme campo"],
    imageLabel: "FOTO · Gorra plana negra · vista frontal",
    relacionados: ["polo-pima", "polo-dry-fit", "casaca-softshell"],
  },
  {
    slug: "polo-dry-fit",
    name: "Polo deportivo dry-fit",
    fam: "textil", moq: 25,
    lead: "Tela técnica que seca rápido. Para activaciones, equipos y eventos al aire libre.",
    desc: "Polo deportivo con tela 100% poliéster dry-fit, gramaje 140gr/m². Tejido de alta transpirabilidad y secado rápido. Personalización por sublimación full color, perfecta para diseños complejos sobre toda la prenda.",
    materials: ["Poliéster 100% dry-fit", "Tejido 140 gr/m²", "Costura plana"],
    colors: ["Sublimación full color (cualquier diseño)"],
    tecnicas: ["Sublimación full prenda (recomendado)", "Serigrafía localizada"],
    usos: ["Equipos deportivos corporativos", "Carreras y eventos", "Activaciones outdoor"],
    imageLabel: "FOTO · Polo dry-fit sublimado",
    relacionados: ["polo-pima", "gorra-plana", "tote-bag"],
  },
  {
    slug: "tomatodo-inox",
    name: "Tomatodo acero inoxidable",
    fam: "cocina", moq: 50, hot: true,
    lead: "Doble pared, tapa hermética, 500ml. El compañero de escritorio que todos terminan usando.",
    desc: "Tomatodo de acero inoxidable 304 con doble pared, aislamiento térmico de 12 horas frío / 6 horas calor. Capacidad 500ml, tapa con sistema anti-derrame y sorbete metálico incluido. Personalización por grabado láser permanente.",
    materials: ["Acero inox 304 grado alimenticio", "Doble pared aislante", "Tapa hermética", "Sorbete metálico incluido"],
    colors: ["Acero natural", "Negro mate", "Blanco mate", "Pantone a pedido (+MOQ)"],
    tecnicas: ["Grabado láser (recomendado)", "Impresión UV", "Pintura electrostática"],
    usos: ["Welcome kit", "Regalo corporativo", "Sostenibilidad / wellness"],
    imageLabel: "FOTO · Tomatodo inox negro mate",
    relacionados: ["termo-personalizado", "taza-ceramica", "lonchera-ejecutiva"],
  },
  {
    slug: "taza-ceramica",
    name: "Taza cerámica sublimada",
    fam: "cocina", moq: 36,
    lead: "11oz, vajilla blanca o de color, sublimación full color en 360°.",
    desc: "Taza de cerámica blanca o de color, capacidad 11oz, asa reforzada. Sublimación full color en 360°, apta para microondas y lavavajillas. Empaque individual en caja blanca incluido.",
    materials: ["Cerámica vajilla AAA", "Recubrimiento sublimable", "Apta microondas"],
    colors: ["Blanca", "Mágica (cambia con calor)", "Interior color", "Negra mate"],
    tecnicas: ["Sublimación 360° full color", "Sublimación parcial"],
    usos: ["Welcome kit", "Regalo cliente", "Eventos navideños", "Premios"],
    imageLabel: "FOTO · Taza cerámica sublimada · pareja",
    relacionados: ["tomatodo-inox", "termo-personalizado", "caja-regalo"],
  },
  {
    slug: "termo-personalizado",
    name: "Termo personalizado 500ml",
    fam: "cocina", moq: 50,
    lead: "Acero inox, 24h frío / 12h calor, sello hermético. Para los que viajan con café.",
    desc: "Termo de acero inoxidable doble pared, 500ml. Aislamiento térmico de 24 horas frío / 12 horas calor. Tapa con seguro hermético, base antideslizante. Acabados disponibles en mate o brillante.",
    materials: ["Acero inox 304", "Doble pared al vacío", "Base antideslizante", "Sello hermético"],
    colors: ["Negro mate", "Blanco mate", "Acero", "Verde militar", "Burdeos"],
    tecnicas: ["Grabado láser", "Impresión UV", "Pintura electrostática"],
    usos: ["Regalo ejecutivo", "Premio anual", "Onboarding equipo campo"],
    imageLabel: "FOTO · Termo acero negro mate",
    relacionados: ["tomatodo-inox", "lonchera-ejecutiva"],
  },
  {
    slug: "lonchera-ejecutiva",
    name: "Lonchera ejecutiva",
    fam: "cocina", moq: 25,
    lead: "Tela técnica, divisiones interiores, asa reforzada. Para los almuerzos de oficina serios.",
    desc: "Lonchera térmica con interior aislante de aluminio, exterior en tela técnica resistente al agua. Compartimentos para envases, botella y cubiertos. Personalización por bordado o transfer térmico.",
    materials: ["Tela poliéster 600D", "Aislante aluminio", "Cierre YKK", "Asa reforzada"],
    colors: ["Negro", "Gris", "Navy"],
    tecnicas: ["Bordado", "Transfer térmico", "Etiqueta tejida"],
    usos: ["Wellness program", "Welcome kit", "Programa sostenibilidad"],
    imageLabel: "FOTO · Lonchera ejecutiva negra",
    relacionados: ["tomatodo-inox", "termo-personalizado", "mochila-ejecutiva"],
  },
  {
    slug: "usb-tipo-c",
    name: "USB tipo C 32GB",
    fam: "tech", moq: 50,
    lead: "USB-C reversible, 32GB de fábrica, carcasa metálica. El detalle tech que sí se usa.",
    desc: "Memoria USB tipo C reversible, capacidad 32GB. Carcasa de aluminio con anillo para llavero. Compatible con laptops, tablets y celulares modernos. Personalización por grabado láser o impresión UV.",
    materials: ["Aluminio anodizado", "Chip USB 3.0 32GB", "Conector tipo C reversible"],
    colors: ["Negro", "Plata", "Dorado", "Color a pedido"],
    tecnicas: ["Grabado láser", "Impresión UV full color"],
    usos: ["Conferencias y eventos B2B", "Regalo cliente", "Onboarding ejecutivo"],
    imageLabel: "FOTO · USB-C aluminio negro",
    relacionados: ["power-bank", "mouse-pad", "audifonos-bt"],
  },
  {
    slug: "power-bank",
    name: "Power bank 10.000mAh",
    fam: "tech", moq: 25, hot: true,
    lead: "10.000mAh, doble entrada USB-C y micro, carga 2 dispositivos a la vez.",
    desc: "Power bank de 10.000mAh con doble salida USB-A y entrada USB-C / micro USB. Indicador LED de batería, protección contra sobrecarga. Carcasa aluminio o ABS. Personalización por grabado láser o impresión UV.",
    materials: ["Batería litio polímero", "Carcasa aluminio/ABS", "Cable USB-C incluido"],
    colors: ["Negro", "Blanco", "Plata", "Color a pedido (MOQ 100)"],
    tecnicas: ["Grabado láser", "Impresión UV full color", "Pad printing"],
    usos: ["Regalo ejecutivo premium", "Onboarding", "Premio recurrente"],
    imageLabel: "FOTO · Power bank negro · lay flat",
    relacionados: ["usb-tipo-c", "audifonos-bt", "mouse-pad"],
  },
  {
    slug: "mouse-pad",
    name: "Mouse pad branded",
    fam: "tech", moq: 50,
    lead: "Superficie sublimable full color, base antideslizante, esquinas suaves.",
    desc: "Mouse pad rectangular o personalizado en forma, base de caucho antideslizante. Superficie con tela sublimable que permite impresión full color en toda el área. Bordes cosidos opcionales para mayor durabilidad.",
    materials: ["Base caucho 3mm", "Superficie tela sublimable", "Bordes cosidos opcional"],
    colors: ["Sublimación full color"],
    tecnicas: ["Sublimación full área (recomendado)", "Forma a medida"],
    usos: ["Onboarding home office", "Welcome kit", "Material de oficina"],
    imageLabel: "FOTO · Mouse pad branded · sobre escritorio",
    relacionados: ["usb-tipo-c", "power-bank"],
  },
  {
    slug: "audifonos-bt",
    name: "Audífonos bluetooth",
    fam: "tech", moq: 25,
    lead: "Bluetooth 5.0, hasta 8h de batería, estuche de carga incluido.",
    desc: "Audífonos in-ear inalámbricos Bluetooth 5.0, autonomía de hasta 8 horas con estuche de carga. Resistentes al sudor (IPX4), controles táctiles. Personalización en estuche por grabado láser o impresión UV.",
    materials: ["Drivers 13mm", "Bluetooth 5.0", "Estuche carga incluido", "Resistente al sudor IPX4"],
    colors: ["Negro", "Blanco"],
    tecnicas: ["Grabado láser en estuche", "Impresión UV full color"],
    usos: ["Premio ejecutivo", "Wellness program", "Regalo de fin de año"],
    imageLabel: "FOTO · Audífonos bluetooth negros + estuche",
    relacionados: ["power-bank", "usb-tipo-c"],
  },
  {
    slug: "bolsa-tocuyo",
    name: "Bolsa tocuyo sublimada",
    fam: "bolsas", moq: 100, hot: true,
    lead: "Tela de tocuyo natural, asa larga, sublimación full color en toda la cara.",
    desc: "Bolsa de tela tocuyo 100% algodón, medidas 35x40cm con fuelle de 10cm. Asa larga reforzada. Sublimación full color a un lado o doble cara. Reutilizable, lavable y sostenible.",
    materials: ["Tocuyo 100% algodón", "Asa larga reforzada", "Costura doble"],
    colors: ["Natural (sublimable)", "Negra", "Crema"],
    tecnicas: ["Sublimación a 1 cara (recomendado)", "Sublimación doble cara", "Serigrafía"],
    usos: ["Eventos masivos", "Activaciones retail", "Welcome bag", "Giveaway sostenible"],
    imageLabel: "FOTO · Bolsa tocuyo branded",
    relacionados: ["tote-bag", "mochila-ejecutiva", "lanyard-sublimado"],
  },
  {
    slug: "mochila-ejecutiva",
    name: "Mochila ejecutiva",
    fam: "bolsas", moq: 25,
    lead: "Compartimento laptop, organizador interno, tela impermeable. La mochila que sí se va a usar todos los días.",
    desc: "Mochila ejecutiva con compartimento acolchado para laptop 15.6\", organizador frontal, salida para auriculares y puerto USB lateral. Tela poliéster impermeable, cierres YKK. Personalización por bordado o transfer.",
    materials: ["Poliéster 1680D impermeable", "Cierres YKK", "Compartimento laptop acolchado", "Puerto USB lateral"],
    colors: ["Negro", "Gris carbón", "Navy"],
    tecnicas: ["Bordado frontal", "Transfer térmico", "Etiqueta tejida"],
    usos: ["Onboarding ejecutivo", "Regalo premium", "Programa retención talento"],
    imageLabel: "FOTO · Mochila ejecutiva negra · vista 3/4",
    relacionados: ["casaca-softshell", "lonchera-ejecutiva", "set-cuero-premium"],
  },
  {
    slug: "tote-bag",
    name: "Tote bag impreso",
    fam: "bolsas", moq: 100,
    lead: "Tocuyo o canvas, asa larga, ideal para eventos masivos. Económica y efectiva.",
    desc: "Tote bag de tela tocuyo o canvas, asas largas, fondo plano. Personalización por serigrafía o estampado directo. La bolsa ideal para eventos de gran volumen con buen costo por unidad.",
    materials: ["Tocuyo o canvas 100% algodón", "Asas largas reforzadas"],
    colors: ["Natural", "Negra", "Crema"],
    tecnicas: ["Serigrafía (recomendado)", "Estampado directo", "Sublimación"],
    usos: ["Eventos masivos", "Conferencias", "Goodie bag retail"],
    imageLabel: "FOTO · Tote bag impreso negro",
    relacionados: ["bolsa-tocuyo", "lanyard-sublimado"],
  },
  {
    slug: "lanyard-sublimado",
    name: "Lanyard sublimado",
    fam: "bolsas", moq: 100,
    lead: "Sublimación full color, gancho metálico, porta-credencial. Para tu evento o staff.",
    desc: "Cordón portacredencial sublimado full color, ancho de 15mm o 20mm. Gancho metálico tipo cocodrilo o pulpo. Porta-credencial transparente opcional. Producción rápida desde 3 días hábiles.",
    materials: ["Poliéster sublimable", "Gancho metálico", "Porta-credencial opcional"],
    colors: ["Sublimación full color"],
    tecnicas: ["Sublimación full largo (recomendado)"],
    usos: ["Eventos y conferencias", "Identificación staff", "Activaciones"],
    imageLabel: "FOTO · Lanyards sublimados · varios",
    relacionados: ["bolsa-tocuyo", "tote-bag", "llavero-pvc"],
  },
  {
    slug: "set-cuero-premium",
    name: "Set de cuero premium",
    fam: "premium", moq: 10, hot: true, tag: "Edición limitada",
    lead: "Cuero genuino, hecho a mano, en caja de regalo. Para esos clientes que importan.",
    desc: "Set ejecutivo de cuero genuino: libreta A5 con cierre, porta-tarjetas y bolígrafo. Cuero curtido vegetal, costura a mano, herrajes en bronce. Cada pieza grabada en frío o relieve. Presentación en caja rígida de regalo.",
    materials: ["Cuero genuino curtido vegetal", "Costura a mano", "Herrajes bronce", "Caja regalo rígida"],
    colors: ["Negro", "Caramelo", "Marrón oscuro"],
    tecnicas: ["Grabado en frío", "Hot stamping dorado/plata", "Relieve seco"],
    usos: ["Cliente top-tier", "Premio CEO", "Regalo aniversario corporativo"],
    imageLabel: "FOTO · Set cuero caramelo · libreta + porta-tarjetas",
    relacionados: ["caja-regalo", "libreta-cuero", "vino-custom"],
  },
  {
    slug: "caja-regalo",
    name: "Caja regalo curada",
    fam: "premium", moq: 10,
    lead: "Curaduría de 4-6 piezas, empaque a la medida, listo para entregar.",
    desc: "Caja regalo armada por nuestro equipo: te ayudamos a curar entre 4 y 6 piezas según ocasión (Navidad, aniversario, onboarding ejecutivo). Empaque rígido con foam interior, papel de seda, tarjeta personalizada. Lista para entregar en tu evento o despachar a domicilio.",
    materials: ["Caja rígida foam interior", "Papel de seda branded", "Tarjeta personalizada", "Cinta satinada"],
    colors: ["Negra", "Blanca", "Madera", "Color a pedido"],
    tecnicas: ["Hot stamping dorado/plata", "Impresión CMYK", "Grabado en relieve"],
    usos: ["Navidad corporativa", "Onboarding C-level", "Aniversario empresa"],
    imageLabel: "FOTO · Caja regalo abierta · contenido curado",
    relacionados: ["set-cuero-premium", "vino-custom", "libreta-cuero"],
  },
  {
    slug: "libreta-cuero",
    name: "Libreta cuero + lapicero",
    fam: "premium", moq: 25,
    lead: "Libreta A5 en cuero genuino, lapicero metálico a juego, en estuche.",
    desc: "Set de libreta A5 con tapa de cuero genuino y lapicero metálico a juego. Encuadernación cosida, 120 hojas bond crema. Cierre de banda elástica. Presentación en estuche rígido.",
    materials: ["Tapa cuero genuino", "Hojas bond crema 80gr · 120pp", "Banda elástica", "Estuche rígido"],
    colors: ["Negro", "Caramelo", "Marrón"],
    tecnicas: ["Grabado en frío", "Hot stamping", "Relieve"],
    usos: ["Regalo ejecutivo", "Aniversario corporativo", "Premio"],
    imageLabel: "FOTO · Libreta cuero + lapicero en estuche",
    relacionados: ["set-cuero-premium", "caja-regalo", "libreta-a5"],
  },
  {
    slug: "vino-custom",
    name: "Vino con etiqueta custom",
    fam: "premium", moq: 12,
    lead: "Vinos de bodega, etiqueta diseñada con tu marca, en estuche listo para regalo.",
    desc: "Botella de vino tinto reserva (cepas seleccionadas a tu pedido) con etiqueta diseñada por nuestro equipo bajo tu identidad de marca. Presentación en estuche rígido o caja de madera para 1, 2 o 3 botellas.",
    materials: ["Vino reserva 750ml", "Etiqueta papel adhesivo premium", "Estuche rígido o caja madera"],
    colors: ["Tinto", "Blanco", "Rosé"],
    tecnicas: ["Etiqueta CMYK", "Hot stamping en estuche", "Tarjeta dedicatoria"],
    usos: ["Regalo navideño C-level", "Aniversario", "Cierre de año cliente top"],
    imageLabel: "FOTO · Vino con etiqueta custom + estuche",
    relacionados: ["caja-regalo", "set-cuero-premium"],
  },
];

// helpers
function getProductBySlug(slug) {
  return PRODUCTOS.find(p => p.slug === slug);
}
function getCategoryLabel(famId) {
  return CATEGORIAS.find(c => c.id === famId)?.label || "";
}

// portafolio
const CASOS = [
  { client: "D-LINK PERÚ", title: "Kit onboarding 2026", cat: "Onboarding · 2026",
    stats: [{ num: "1.400", lbl: "piezas" }, { num: "7d", lbl: "entrega" }, { num: "100%", lbl: "QC" }],
    label: "FOTO · Kit D-LINK desplegado sobre fondo negro", size: "big",
    desc: "Bienvenida corporativa para el equipo entrante: libretas, lapiceros, llaveros, lanyards y tomatodos en kit cerrado." },
  { client: "Banco Pichincha", title: "Regalos ejecutivos fin de año", cat: "Premium · 2024",
    stats: [{ num: "350", lbl: "kits" }, { num: "12d", lbl: "entrega" }, { num: "2", lbl: "ciudades" }],
    label: "FOTO · Caja cuero + libreta",
    desc: "Curaduría premium para clientes top-tier en Lima y Guayaquil: set cuero + vino + caja regalo." },
  { client: "Festival Selvámonos", title: "Merch de evento completo", cat: "Eventos · 2024",
    stats: [{ num: "2.800", lbl: "prendas" }, { num: "9d", lbl: "entrega" }, { num: "4", lbl: "sku" }],
    label: "FOTO · Mesa de merch en festival",
    desc: "Polos, gorras, totes y lanyards para 3 días de festival. Stock listo en Día -1 en sede." },
  { client: "ONG +Educación", title: "Mochilas escolares", cat: "Educación · 2024",
    stats: [{ num: "1.000", lbl: "mochilas" }, { num: "15d", lbl: "entrega" }, { num: "3", lbl: "regiones" }],
    label: "FOTO · Mochila branded + cajas", size: "big",
    desc: "Mil mochilas branded entregadas en tres regiones del país: Lima, Cusco y Cajamarca." },
  { client: "Backus", title: "Activación verano", cat: "Eventos · 2025",
    stats: [{ num: "4.500", lbl: "piezas" }, { num: "5d", lbl: "express" }, { num: "8", lbl: "playas" }],
    label: "FOTO · Polos y gorras Backus",
    desc: "Activación de verano cubierta de Punta Sal a Asia: polos dry-fit, gorras y giveaways." },
  { client: "PUCP", title: "Welcome pack docentes", cat: "Educación · 2024",
    stats: [{ num: "220", lbl: "kits" }, { num: "10d", lbl: "entrega" }, { num: "100%", lbl: "QC" }],
    label: "FOTO · Welcome pack docente PUCP",
    desc: "Kit de bienvenida para nuevos docentes: libreta, lapicero premium y tomatodo branded." },
];

const TESTIMONIOS = [
  { quote: "Nos resolvieron los kits de onboarding de un trimestre completo sin que tuviéramos que preocuparnos por nada. Cumplieron cada plazo que nos prometieron, sin sustos.",
    name: "Anthony Bancho", role: "People Ops · D-LINK Perú", initials: "AB" },
  { quote: "Un solo proveedor para textil, libretas y empaque. Tres semanas menos de coordinación, y la calidad fue mejor de la que esperaba.",
    name: "María Sotelo", role: "Marketing · Banco Pichincha", initials: "MS" },
  { quote: "Avisaron de un cambio de material antes de producir y lo resolvieron sin costo extra. Eso es ser aliado, no proveedor.",
    name: "Carlos Quintana", role: "Brand · Selvámonos", initials: "CQ" },
];

const CLIENTS = [
  { name: "NVIDIA",   logo: "assets/clients/NVIDIA.svg",   h: 26 },
  { name: "AMD",      logo: "assets/clients/AMD.svg",      h: 22 },
  { name: "Intel",    logo: "assets/clients/INTEL.svg",    h: 24 },
  { name: "Aorus",    logo: "assets/clients/AORUS.svg",    h: 24 },
  { name: "Moonton",  logo: "assets/clients/MOONTON.svg",  h: 22 },
  { name: "Rivalry",  logo: "assets/clients/RIVALRY.svg",  h: 30 },
  { name: "Yape",     logo: "assets/clients/YAPE.svg",     h: 47 },
  { name: "SPDA",     logo: "assets/clients/SPDA.svg",     h: 30 },
  { name: "PUCP",     logo: "assets/clients/PUCP.svg",     h: 30 },
  { name: "UTP",      logo: "assets/clients/UTP.svg",      h: 28 },
];

const FAQS = [
  { q: "¿Cuánto demora una cotización?",
    a: "Lo más rápido que podamos — te respondemos el mismo día confirmando que recibimos tu brief. El detalle de la cotización formal toma usualmente entre 2 y 4 días hábiles según la complejidad. Si es urgente, dilo y lo movemos." },
  { q: "¿Tienen cantidad mínima por producto?",
    a: "Depende del producto y la técnica. Serigrafía desde 50; sublimación y bordado desde 25; regalos ejecutivos desde 10. Pregúntanos por el tuyo." },
  { q: "¿Trabajan fuera de Lima?",
    a: "Sí. Entregamos en Lima y despachamos a provincia con operadores logísticos. Te enviamos guía y coordinamos horarios." },
  { q: "¿Siempre hacen muestras antes de producir?",
    a: "Siempre. Antes de producir el lote completo te enviamos una muestra física o digital. Sin tu OK, no producimos." },
  { q: "¿Y si algo sale con falla?",
    a: "Reponemos sin costo. QC pieza por pieza, pero si algo se nos pasa, lo asumimos nosotros — no tú." },
  { q: "¿Facturan y aceptan crédito?",
    a: "Sí. Factura y boleta electrónica, detracción cuando aplica y crédito para clientes recurrentes." },
];

const SERVICES = [
  { id: "merch", title: "Merch corporativo",
    desc: "El día a día de tu marca: lapiceros, libretas, tomatodos, polos y todo lo que necesite tu equipo.",
    tags: ["Producción", "Personalización", "Stock"],
    long: "Producimos al por mayor y a tu medida los productos básicos que tu marca necesita para estar presente. Trabajamos con un catálogo de más de 200 SKUs y red de proveedores que nos permite responder rápido con calidad consistente. Si lo usas tú o tu equipo, lo hacemos.",
    includes: ["Catálogo curado de 200+ productos", "Personalización en bordado, serigrafía, sublimación, grabado láser", "Reposiciones desde stock para clientes recurrentes", "Asesor dedicado por cuenta"] },
  { id: "onboarding", title: "Kits de onboarding",
    desc: "Bienvenidas que se sienten. Diseñamos y armamos el kit completo, empaque incluido.",
    tags: ["Curaduría", "Armado", "Envío"],
    long: "El primer día en tu empresa cuenta. Diseñamos welcome kits para tu equipo nuevo: curaduría de piezas, armado del kit, empaque branded y, si quieres, entrega a domicilio del trabajador. Llave en mano.",
    includes: ["Curaduría con base en tu cultura de marca", "Empaque rígido o flexible branded", "Tarjeta dedicatoria personalizada", "Envío a domicilio en Lima y provincia"] },
  { id: "regalos", title: "Regalos ejecutivos",
    desc: "Detalles que cuentan algo. Selección premium, personalizada y con presentación a la altura.",
    tags: ["Cuero", "Madera", "Edición limitada"],
    long: "Para los clientes top, las fechas que importan y los aniversarios que se cuentan en años. Cuero genuino, madera, edición limitada — con presentación de regalo y tarjeta dedicatoria.",
    includes: ["Selección con base en perfil del destinatario", "Edición limitada (numerada opcional)", "Presentación premium con caja rígida", "Logística punto-a-punto"] },
  { id: "eventos", title: "Eventos & activaciones",
    desc: "Cubrimos el merch de tu evento end-to-end. Listo el día D, en el lugar.",
    tags: ["Polos", "Lanyards", "Giveaways"],
    long: "Tu evento merece más que un proveedor que entregue cajas. Nos encargamos del merch de toda la activación: staff, asistentes, giveaways, escenografía blanda. Stock pre-ubicado el día anterior.",
    includes: ["Producción rápida (3-5 días express)", "Logística pre-ubicada el día -1", "Reposiciones express en evento", "Coordinación con tu agencia o equipo BTL"] },
  { id: "textil", title: "Textil & uniformes",
    desc: "Polos, casacas y uniformes con bordado, estampado o sublimación. Tallas reales, stock para reposiciones.",
    tags: ["Bordado", "Sublimado", "Serigrafía"],
    long: "Uniformamos a tu equipo con prendas que sí quieren usar. Algodón pima, dry-fit, softshell — bordado, sublimado o estampado. Programa de tallas reales y stock de reposición para nuevos ingresos.",
    includes: ["Programa de tallaje por trabajador", "Stock de reposición disponible 12 meses", "Catálogo textil corporativo", "Etiquetas tejidas custom (cuello)"] },
  { id: "empaque", title: "Empaque & branding",
    desc: "Lo que convierte un producto en regalo: cajas, sleeves, tarjetas, papel de seda — diseñado y producido acá.",
    tags: ["Cajas", "Tarjetas", "Stickers"],
    long: "El empaque es el primer impacto. Diseñamos y producimos cajas, sleeves, tarjetas, papel de seda y stickers — para que tu producto llegue como regalo, no como envío.",
    includes: ["Diseño estructural y gráfico", "Cajas rígidas y plegables", "Papel de seda + stickers branded", "Tarjetas dedicatoria con hot stamping"] },
];

const PROCESO = [
  { num: "01", title: "Nos cuentas",
    desc: "Brief por correo, llamada o WhatsApp. Lo importante: para qué, para quién, para cuándo.",
    detail: "No hace falta brief perfecto. Una idea, un par de fotos de inspiración, una fecha límite y un rango de presupuesto bastan para arrancar. Si no sabes por dónde, te guía un asesor.",
    time: "Día 0" },
  { num: "02", title: "Te cotizamos",
    desc: "Recibes tu cotización detallada con productos, materiales, plazos y opciones. Sin sorpresas, sin costos ocultos.",
    detail: "Te confirmamos recibo el mismo día y armamos la cotización formal en pocos días hábiles — usualmente entre 2 y 4, según la complejidad. Si es urgente, lo movemos. Recibes un PDF con técnica, materiales, plazos, alternativas e IGV desglosado.",
    time: "2–4 días" },
  { num: "03", title: "Aprobamos muestras",
    desc: "Antes de producir todo, te enviamos una muestra. Color, acabado y arte aprobados por ti.",
    detail: "Para producciones por mayor, te enviamos una muestra física o digital del producto terminado antes de cerrar la producción del lote completo. Si algo no calza, lo corregimos antes de que sea tarde.",
    time: "Día 3–5" },
  { num: "04", title: "Producimos",
    desc: "Talleres propios y red de aliados en Lima. QC pieza por pieza antes de salir.",
    detail: "Producción en nuestros talleres y proveedores de confianza, todos en Lima. Cada pieza pasa control de calidad antes de empacarse. Te enviamos fotos del lote terminado.",
    time: "5–10 días" },
  { num: "05", title: "Entregamos",
    desc: "A tu oficina, evento o despacho descentralizado. Tú firmas el cargo, listo.",
    detail: "Coordinamos día y hora contigo. Entrega en Lima por nuestra flota, despacho a provincia por operadores logísticos con guía y seguro. Tú firmas cargo, nosotros nos vamos.",
    time: "On-time" },
];

Object.assign(window, {
  CATEGORIAS, PRODUCTOS, CASOS, TESTIMONIOS, CLIENTS, FAQS, SERVICES, PROCESO,
  getProductBySlug, getCategoryLabel,
});
